import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "./providers";
import { RouteChangeListener } from "@/utils/routeChanger"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RouteChangeListener/>
        <AppProvider>
          {children}</AppProvider>
      </body>
    </html>
  );
}
